FROM node:16-alpine as etitango-front-build
WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY ./ /app/
ARG REACT_APP_BACK_END_URL
ENV REACT_APP_BACK_END_URL=${REACT_APP_BACK_END_URL}
ARG REACT_APP_FRONT_END_URL
ENV REACT_APP_FRONT_END_URL=${REACT_APP_FRONT_END_URL}
ARG REACT_APP_API_KEY
ENV REACT_APP_API_KEY=${REACT_APP_API_KEY}
ARG REACT_APP_AUTH_DOMAIN
ENV REACT_APP_AUTH_DOMAIN=${REACT_APP_AUTH_DOMAIN}
ARG REACT_APP_PROJECT_ID
ENV REACT_APP_PROJECT_ID=${REACT_APP_PROJECT_ID}
ARG REACT_APP_STORAGE_BUCKET
ENV REACT_APP_STORAGE_BUCKET=${REACT_APP_STORAGE_BUCKET}
ARG REACT_APP_MESSAGING_SENDER_ID
ENV REACT_APP_MESSAGING_SENDER_ID=${REACT_APP_MESSAGING_SENDER_ID}
ARG REACT_APP_APP_ID
ENV REACT_APP_APP_ID=${REACT_APP_APP_ID}
RUN npm run build

#STAGE 1
FROM nginx:latest as nginx-build
COPY --from=etitango-front-build /app/build /usr/share/nginx/html